
import Foundation

struct Localization {
    static let translations: [AppLanguage: [String: String]] = [
        .english: [
            "Settings": "Settings",
            "Stages": "Stages",
            "Global Config": "Global Config",
            "Blow Threshold (dB)": "Blow Sensitivity",
            "Language": "Language",
            "Done": "Done",
            "Info": "Info",
            "Description": "Description",
            "Type": "Type",
            "Video": "Video",
            "Image": "Image",
            "Source Path": "Source Path",
            "Select Media...": "Select Media...",
            "Playback": "Playback",
            "Mode": "Mode",
            "One Shot": "One Shot",
            "Loop": "Loop",
            "Show Clock": "Show Clock",
            "Triggers": "Triggers",
            "Action": "Action",
            "Target": "Target",
            "Exit App": "Exit App",
            "Save": "Save",
            "Add New Stage": "Add New Stage",
            "Add Trigger": "Add Trigger",
            "No Stage Loaded": "No Stage Loaded",
            "Circle": "Circle",
            "Edit Stage": "Edit Stage",
            "tap_1": "Single Tap",
            "tap_2": "Double Tap",
            "tap_3": "Triple Tap",
            "long_press": "Long Press",
            "blow": "Blow",
            "circle": "Circle"
        ],
        .chinese: [
            "Settings": "设置",
            "Stages": "魔术流程",
            "Global Config": "全局设置",
            "Blow Threshold (dB)": "吹气灵敏度",
            "Language": "语言",
            "Done": "完成",
            "Info": "基本信息",
            "Description": "描述",
            "Type": "类型",
            "Video": "视频",
            "Image": "图片",
            "Source Path": "资源路径",
            "Select Media...": "选择素材...",
            "Playback": "播放设置",
            "Mode": "模式",
            "One Shot": "单次播放",
            "Loop": "循环播放",
            "Show Clock": "显示时钟",
            "Triggers": "触发器",
            "Action": "动作",
            "Target": "目标",
            "Exit App": "退出应用",
            "Save": "保存",
            "Add New Stage": "添加新阶段",
            "Add Trigger": "添加触发器",
            "No Stage Loaded": "未加载魔术",
            "Circle": "画圈",
            "Edit Stage": "编辑阶段",
            "tap_1": "单次点击",
            "tap_2": "双击",
            "tap_3": "三击",
            "long_press": "长按",
            "blow": "吹气",
            "circle": "画圈"
        ],
        .japanese: [
            "Settings": "設定",
            "Stages": "ステージ",
            "Global Config": "基本設定",
            "Blow Threshold (dB)": "息の感度",
            "Language": "言語",
            "Done": "完了",
            "Info": "情報",
            "Description": "説明",
            "Type": "タイプ",
            "Video": "動画",
            "Image": "画像",
            "Source Path": "ソースパス",
            "Select Media...": "メディアを選択...",
            "Playback": "再生",
            "Mode": "モード",
            "One Shot": "一回のみ",
            "Loop": "ループ",
            "Show Clock": "時計を表示",
            "Triggers": "トリガー",
            "Action": "アクション",
            "Target": "ターゲット",
            "Exit App": "アプリを終了",
            "Save": "保存",
            "Add New Stage": "新規ステージ",
            "Add Trigger": "トリガー追加",
            "No Stage Loaded": "ステージなし",
            "Circle": "円を描く",
            "Edit Stage": "ステージ編集",
            "tap_1": "シングルタップ",
            "tap_2": "ダブルタップ",
            "tap_3": "トリプルタップ",
            "long_press": "長押し",
            "blow": "息を吹く",
            "circle": "円を描く"
        ],
        .french: [
            "Settings": "Paramètres",
            "Stages": "Étapes",
            "Global Config": "Config Globale",
            "Blow Threshold (dB)": "Sensibilité Souffle",
            "Language": "Langue",
            "Done": "Terminé",
            "Info": "Info",
            "Description": "Description",
            "Type": "Type",
            "Video": "Vidéo",
            "Image": "Image",
            "Source Path": "Chemin Source",
            "Select Media...": "Choisir Média...",
            "Playback": "Lecture",
            "Mode": "Mode",
            "One Shot": "Une fois",
            "Loop": "Boucle",
            "Show Clock": "Afficher l'heure",
            "Triggers": "Déclencheurs",
            "Action": "Action",
            "Target": "Cible",
            "Exit App": "Quitter",
            "Save": "Sauvegarder",
            "Add New Stage": "Ajouter Étape",
            "Add Trigger": "Ajouter Déclencheur",
            "No Stage Loaded": "Aucune Étape",
            "Circle": "Cercle",
            "Edit Stage": "Modifier Étape",
            "tap_1": "Simple Tape",
            "tap_2": "Double Tape",
            "tap_3": "Triple Tape",
            "long_press": "Appui Long",
            "blow": "Souffler",
            "circle": "Cercle"
        ],
        .german: [
            "Settings": "Einstellungen",
            "Stages": "Phasen",
            "Global Config": "Globale Konfig",
            "Blow Threshold (dB)": "Pusteempfindlichkeit",
            "Language": "Sprache",
            "Done": "Fertig",
            "Info": "Info",
            "Description": "Beschreibung",
            "Type": "Typ",
            "Video": "Video",
            "Image": "Bild",
            "Source Path": "Quellpfad",
            "Select Media...": "Medien wählen...",
            "Playback": "Wiedergabe",
            "Mode": "Modus",
            "One Shot": "Einmalig",
            "Loop": "Schleife",
            "Show Clock": "Uhr anzeigen",
            "Triggers": "Auslöser",
            "Action": "Aktion",
            "Target": "Ziel",
            "Exit App": "Beenden",
            "Save": "Speichern",
            "Add New Stage": "Phase hinzufügen",
            "Add Trigger": "Auslöser hinzufügen",
            "No Stage Loaded": "Keine Phase",
            "Circle": "Kreis",
            "Edit Stage": "Phase bearbeiten",
            "tap_1": "Tippen",
            "tap_2": "Doppeltippen",
            "tap_3": "Dreifachtippen",
            "long_press": "Lange drücken",
            "blow": "Pusten",
            "circle": "Kreis"
        ],
        .spanish: [
            "Settings": "Ajustes",
            "Stages": "Etapas",
            "Global Config": "Config Global",
            "Blow Threshold (dB)": "Sensibilidad Soplo",
            "Language": "Idioma",
            "Done": "Listo",
            "Info": "Info",
            "Description": "Descripción",
            "Type": "Tipo",
            "Video": "Video",
            "Image": "Imagen",
            "Source Path": "Ruta de Fuente",
            "Select Media...": "Seleccionar Medio...",
            "Playback": "Reproducción",
            "Mode": "Modo",
            "One Shot": "Una vez",
            "Loop": "Bucle",
            "Show Clock": "Mostrar Reloj",
            "Triggers": "Disparadores",
            "Action": "Acción",
            "Target": "Objetivo",
            "Exit App": "Salir",
            "Save": "Guardar",
            "Add New Stage": "Nueva Etapa",
            "Add Trigger": "Nuevo Disparador",
            "No Stage Loaded": "Sin Etapa",
            "Circle": "Círculo",
            "Edit Stage": "Editar Etapa",
            "tap_1": "Toque Simple",
            "tap_2": "Toque Doble",
            "tap_3": "Toque Triple",
            "long_press": "Pulsación Larga",
            "blow": "Soplar",
            "circle": "Círculo"
        ]
    ]
    
    static func get(_ key: String, for language: AppLanguage) -> String {
        return translations[language]?[key] ?? key
    }
}
